[2022-08-18 22:50:03,901] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: elastic_desk.popula_elastic_finalizados scheduled__2022-08-18T22:45:00+00:00 [queued]>
[2022-08-18 22:50:03,913] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: elastic_desk.popula_elastic_finalizados scheduled__2022-08-18T22:45:00+00:00 [queued]>
[2022-08-18 22:50:03,914] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 22:50:03,914] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-18 22:50:03,914] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-18 22:50:03,936] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): popula_elastic_finalizados> on 2022-08-18 22:45:00+00:00
[2022-08-18 22:50:03,940] {standard_task_runner.py:52} INFO - Started process 24465 to run task
[2022-08-18 22:50:03,957] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'elastic_desk', 'popula_elastic_finalizados', 'scheduled__2022-08-18T22:45:00+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/etl_elastic_desk.py', '--cfg-path', '/tmp/tmpy7vxaeow', '--error-file', '/tmp/tmpzy2rm617']
[2022-08-18 22:50:03,958] {standard_task_runner.py:80} INFO - Job 179: Subtask popula_elastic_finalizados
[2022-08-18 22:50:04,162] {task_command.py:371} INFO - Running <TaskInstance: elastic_desk.popula_elastic_finalizados scheduled__2022-08-18T22:45:00+00:00 [running]> on host 1e1070d9e5ae
[2022-08-18 22:50:04,301] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clecio.antao@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=elastic_desk
AIRFLOW_CTX_TASK_ID=popula_elastic_finalizados
AIRFLOW_CTX_EXECUTION_DATE=2022-08-18T22:45:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-18T22:45:00+00:00
[2022-08-18 22:50:04,310] {base.py:271} INFO - GET http://192.168.2.100:9200/ [status:200 request:0.006s]
[2022-08-18 22:50:08,949] {base.py:271} INFO - HEAD http://192.168.2.100:9200/_template/desk_finalizados [status:200 request:0.022s]
[2022-08-18 22:50:09,579] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/es_pandas/es_pandas.py:58 RuntimeWarning: invalid value encountered in double_scalars
[2022-08-18 22:50:09,926] {base.py:271} INFO - POST http://192.168.2.100:9200/_bulk [status:200 request:0.124s]
[2022-08-18 22:50:10,159] {base.py:271} INFO - POST http://192.168.2.100:9200/_bulk [status:200 request:0.142s]
[2022-08-18 22:50:10,370] {base.py:271} INFO - POST http://192.168.2.100:9200/_bulk [status:200 request:0.086s]
[2022-08-18 22:50:10,822] {base.py:271} INFO - POST http://192.168.2.100:9200/_bulk [status:200 request:0.102s]
[2022-08-18 22:50:11,264] {base.py:271} INFO - POST http://192.168.2.100:9200/_bulk [status:200 request:0.100s]
[2022-08-18 22:50:11,611] {base.py:271} INFO - POST http://192.168.2.100:9200/_bulk [status:200 request:0.091s]
[2022-08-18 22:50:12,003] {base.py:271} INFO - POST http://192.168.2.100:9200/_bulk [status:200 request:0.148s]
[2022-08-18 22:50:12,672] {base.py:271} INFO - POST http://192.168.2.100:9200/_bulk [status:200 request:0.150s]
[2022-08-18 22:50:13,360] {base.py:271} INFO - POST http://192.168.2.100:9200/_bulk [status:200 request:0.298s]
[2022-08-18 22:50:13,613] {base.py:271} INFO - POST http://192.168.2.100:9200/_bulk [status:200 request:0.304s]
[2022-08-18 22:50:13,720] {logging_mixin.py:115} INFO - 0       18-08-2022
1       18-08-2022
2       18-08-2022
3       18-08-2022
4       18-08-2022
           ...    
4789    19-07-2022
4790    19-07-2022
4791    19-07-2022
4792    19-07-2022
4793    19-07-2022
Name: DataFinalizacao, Length: 4794, dtype: object
[2022-08-18 22:50:13,738] {python.py:173} INFO - Done. Returned value was: None
[2022-08-18 22:50:14,135] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=elastic_desk, task_id=popula_elastic_finalizados, execution_date=20220818T224500, start_date=20220818T225003, end_date=20220818T225014
[2022-08-18 22:50:14,565] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-08-18 22:50:14,597] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 24465. PIDs of all processes in the group: [24465]
[2022-08-18 22:50:14,597] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 24465
[2022-08-18 22:50:14,751] {process_utils.py:75} INFO - Process psutil.Process(pid=24465, status='terminated', exitcode=0, started='22:50:03') (24465) terminated with exit code 0
